platform :ios, '10.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

use_frameworks!

def run_script_brand
  script_phase :name => 'Run Flutter Firebase',
      :script => "INFO_PLIST=GoogleService-Info.plist\nINFO_FILE=\"${PROJECT_DIR}/Runner/GoogleService-Info.plist\"\n\necho \"Looking for ${INFO_PLIST} in ${INFO_FILE}\"\nif [ ! -f $INFO_FILE ]\nthen\n\techo \"Não foi encontrado o arquivo ${INFO_FILE}.\"\n\texit 1\nfi\n\nPLIST_DESTINATION=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app\necho \"Will copy ${INFO_PLIST} to final destination: ${PLIST_DESTINATION}\"\n\necho \"Using ${INFO_FILE}\"\ncp \"${INFO_FILE}\" \"${PLIST_DESTINATION}\""
end

$FirebaseSDKVersion = '8.15.0'

target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
  
  run_script_brand
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      if Gem::Version.new('10.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end